Repository Kusitms-30th-LetsCareer-B/LetsCareer-FE, pull requests merged in 2024-08, with the labels that each got.

#2 [chore] 개발 환경 세팅
  .github/ISSUE_TEMPLATE/-issue_template.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/App.tsx
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 🧭 Chore

#4 [feat] tailwindcss setting
  .prettier
  package-lock.json
  package.json
Labels: 🚀 Feat

#6 [chore] directory setting
  src/components/Calendar.tsx
  src/components/Layout/Footer.tsx
  src/components/Layout/Header.tsx
  src/components/Layout/PlannerSideBar.tsx
  src/pages/Calendar/CalendarPage.tsx
  src/pages/Career/CareerPage.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Status/StatusPage.tsx
  src/shared/api/recruitments.ts
  src/shared/assets/logo.png
  src/shared/hooks/useCalendar.ts
Labels: 🧭 Chore

#9 [design] header publishing
  src/App.tsx
  src/components/Layout/Header.tsx
  src/index.css
  src/shared/assets/hamburger-md-black.svg
  src/shared/assets/logo-gradient-text.svg
  src/shared/assets/logo.svg
  tailwind.config.js
Labels: 🎨 Design

#10 [Design] footer publishing
  src/App.tsx
  src/components/Layout/Footer.tsx
  src/components/Layout/Header.tsx
  src/index.css
  src/shared/assets/blog.png
  src/shared/assets/instagram.png
  src/shared/assets/logo.png
  tailwind.config.js
Labels: 🎨 Design
