Repository Kusitms-30th-LetsCareer-B/LetsCareer-FE, pull requests merged in 2024-09, with the labels that each got.

#41 [feat] api 연동 추가 및 수정
  src/App.tsx
  src/components/Calendar.tsx
  src/components/DatePicker.tsx
  src/components/PopUpDatePicker.tsx
  src/components/ToDoListTool.ts
  src/components/chips/StatusChip.tsx
  src/pages/Calendar/CalendarPage.tsx
  src/pages/Calendar/api/calendarMonthPersonalTodoApiService.ts
  src/pages/Calendar/api/calendarMonthPersonalTodoType.ts
  src/pages/Calendar/api/calendarMonthRecruitTodoApiService.ts
  src/pages/Calendar/api/calendarMonthRecruitTodoType.ts
  src/pages/Calendar/api/errorHandler.ts
  src/pages/Calendar/api/todoApiService.ts
  src/pages/Calendar/api/todoType.ts
  src/pages/Calendar/components/CalendarCareerList.tsx
  src/pages/Calendar/components/CalendarList.tsx
  src/pages/Calendar/components/CalendarPersonalList.tsx
  src/pages/Calendar/components/CalendarTodoList.tsx
  src/pages/Calendar/components/ScheduleButton.tsx
  src/pages/Calendar/components/Test.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Main/api/careerRecruitmentsStatusApiService.ts
  src/pages/Main/api/careerRecruitmentsStatusType.ts
  src/pages/Main/api/careerStatusesNumApiService.ts
  src/pages/Main/api/careerStatusesNumType.ts
  src/pages/Main/api/errorHandler.ts
  src/pages/Main/api/mainTodayApiService.ts
  src/pages/Main/api/mainTodayType.ts
  src/pages/Main/api/mainTodoApiService.ts
  src/pages/Main/api/personalApiService.ts
  src/pages/Main/api/personalType.ts
  src/pages/Main/components/CareerRecruitmentsStatus.tsx
  src/pages/Main/components/CareerStatusNumBoard.tsx
  src/pages/Main/components/MainTodayList.tsx
  src/pages/Main/components/MainTodoList.tsx
  src/pages/ScheduleEnv/ScheduleEnvPage copy.tsx
  src/pages/ScheduleEnv/ScheduleEnvPage.tsx
  src/pages/ScheduleEnv/ScheduleEnvStatus.tsx
  src/pages/ScheduleEnv/api/scheduleApiService.ts
  src/pages/ScheduleEnv/hooks/useSchedule.ts
  src/pages/Status/DetailStatusPage.tsx
  src/pages/Status/RecurringNotePage.tsx
  src/pages/Status/StatusPage.tsx
  src/pages/Status/components/Buttons/DetailStatusButton.tsx
  src/pages/Status/components/Buttons/RecurringNoteButton.tsx
  src/pages/Status/components/Helpers/RecurringNoteHelper.tsx
  src/shared/api/axiosInstance.ts
  src/shared/api/loginInstance.ts
  src/shared/hooks/useCalendar.ts
  src/shared/hooks/useTodoList.ts
Labels: 🚀 Feat

#43 [design] 필살기 경험 페이지 퍼블리싱
  src/App.tsx
  src/pages/Career/CareerPage.tsx
  src/pages/Career/components/CareerHeader.tsx
  src/pages/Career/components/CareerQuestion.tsx
  src/pages/Career/components/CareerToggle.tsx
  src/pages/Career/components/SpecialExperience.tsx
  src/pages/Status/DetailStatusPage.tsx
  src/pages/Status/RecurringNotePage.tsx
  src/pages/Status/StatusPage.tsx
  src/pages/Status/components/Buttons/DetailStatusButton.tsx
  src/pages/Status/components/Helpers/RecurringNoteHelper.tsx
  src/pages/Status/components/Pagination/StatusPagination.tsx
  src/shared/hooks/useStatusPagination.ts
  tailwind.config.js
Labels: 🎨 Design, 🚀 Feat

#46 [feat] todo list api
  src/components/Calendar.tsx
  src/components/chips/TodoListChip.tsx
  src/pages/Calendar/CalendarPage.tsx
  src/pages/Calendar/TestCalendarTodoList.tsx
  src/pages/Calendar/api/calendarMonthPersonalWorksApiService.ts
  src/pages/Calendar/api/calendarMonthPersonalWorksType.ts
  src/pages/Calendar/components/CalendarCareerList.tsx
  src/pages/Calendar/components/CalendarList.tsx
  src/pages/Calendar/components/CalendarPersonalList.tsx
  src/pages/Calendar/components/CalendarTodoListEditable.tsx
  src/pages/Calendar/components/CalendarTodoListFixed.tsx
  src/pages/Calendar/components/ScheduleButton.tsx
Labels: 🎨 Design, 🚀 Feat

#47 [Feat] 각종 페이지 api 연동
  src/App.tsx
  src/components/Calendar.tsx
  src/components/DatePicker.tsx
  src/components/TestCalendar.tsx
  src/components/ToDoListTool.ts
  src/components/chips/CalendarChip.tsx
  src/components/chips/DdayChip.tsx
  src/components/chips/TodoListChip.tsx
  src/pages/Calendar/CalendarPage.tsx
  src/pages/Calendar/api/calendarMonthPersonalWorksApiService.ts
  src/pages/Calendar/api/calendarMonthPersonalWorksType.ts
  src/pages/Calendar/api/calendarMonthRecruitmentsApiService.ts
  src/pages/Calendar/api/calendarMonthRecruitmentsType.ts
  src/pages/Calendar/api/todoDayGroupedByCompanyApiService.ts
  src/pages/Calendar/api/todoDayGroupedByCompanyType.ts
  src/pages/Calendar/components/CalendarCareerList.tsx
  src/pages/Calendar/components/CalendarList.tsx
  src/pages/Calendar/components/CalendarPersonalList.tsx
  src/pages/Calendar/components/CalendarTodoListEditable.tsx
  src/pages/Calendar/components/CalendarTodoListFixed.tsx
  src/pages/Calendar/components/CalendarTodoList_연동전.tsx
  src/pages/Calendar/components/errorHandler.ts
  src/pages/Career/CareerPage.tsx
  src/pages/Career/components/CareerHeader.tsx
  src/pages/Career/components/CareerQuestion.tsx
  src/pages/Career/components/CareerToggle.tsx
  src/pages/Career/components/Resume.tsx
  src/pages/Career/components/SpecialExperience.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Main/api/careerRecruitmentsStatusApiService.ts
  src/pages/Main/api/careerRecruitmentsStatusType.ts
  src/pages/Main/api/careerStatusesNumApiService.ts
  src/pages/Main/api/careerStatusesNumType.ts
  src/pages/Main/api/errorHandler.ts
  src/pages/Main/api/mainTodayApiService.ts
  src/pages/Main/api/mainTodayType.ts
  src/pages/Main/components/CareerStatusNumBoard.tsx
  src/pages/Main/components/MainTodayList.tsx
  src/pages/Main/components/MainTodoList.tsx
  src/pages/ScheduleEnv/ScheduleEnvPage copy.tsx
  src/pages/ScheduleEnv/ScheduleEnvPage.tsx
  src/pages/Status/ArchivingPage.tsx
  src/pages/Status/DetailStatusPage.tsx
  src/pages/Status/NewArchivingPage.tsx
  src/pages/Status/SelfIntroducePage.tsx
  src/pages/Status/SelfIntroductionComponents/GetSpecialExperience.tsx
  src/pages/Status/SelfIntroductionComponents/ShowSpecialExperience.tsx
  src/pages/Status/SelfIntroductionComponents/WriteSelfIntroduction.tsx
  src/pages/Status/components/Buttons/DetailStatusButton.tsx
  src/pages/Status/components/Buttons/SelfIntroduceButton.tsx
  src/pages/Status/components/Helpers/DetailStatusHelper.tsx
  src/pages/Status/components/Helpers/RecurringNoteHelper.tsx
  src/pages/Status/components/Helpers/SelfIntroduceHelper.tsx.tsx
  src/pages/Status/components/Layout/SelfIntroduceLayout.tsx
  src/pages/Status/components/Pagination/RecurringNotePagination.tsx
  src/pages/Status/components/Pagination/SelfIntroducePagination.tsx
  src/pages/Status/components/Pagination/StatusPagination.tsx
  src/shared/hooks/useDate.ts
  src/shared/hooks/useStatusPagination.ts
Labels: 🎨 Design, 🚀 Feat, 🧹 Refactor

#59 [feat] 채용 일정 삭제 api 수정
  src/pages/RecruScheduleEnv/RecruScheduleEnvPage.tsx
  src/pages/Status/DetailStatusPage.tsx
  src/pages/Status/SelfIntroductionComponents/WriteSelfIntroduction.tsx
  src/shared/hooks/useScrap.tsx
Labels: 🎨 Design, 🚀 Feat

#60 [feat] routine api
  src/components/PopUpDatePicker.tsx
  src/pages/Calendar/api/todoDayGroupedByCompanyApiService.ts
  src/pages/Calendar/api/todoDayGroupedByCompanyType.ts
  src/pages/Calendar/components/TodoListEditable.tsx
  src/pages/Calendar/components/TodoListFixed.tsx
  src/pages/Calendar/components/TodoListFixed_20240909_날짜별.tsx
  src/pages/Main/components/MainTodayList.tsx
  src/pages/Status/DetailStatusPage.tsx
  src/pages/Status/components/Todo/ScheduleField.tsx
  src/pages/Status/components/Todo/TodoComponent.tsx
  src/pages/Status/components/Todo/api/todoApiService.ts
  src/pages/Status/components/Todo/api/todoType.ts
  src/pages/Status/components/Todo/components/AddButton.tsx
  src/pages/Status/components/Todo/components/ScheduleField.tsx
  src/pages/Status/components/Todo/components/SettingsModal.tsx
  src/shared/api/routinesApiService.ts
  src/shared/api/routinesType.ts
  src/shared/assets/modify-routine.png
  src/shared/assets/routine-check.png
  src/shared/assets/routine-setting.png
  src/shared/assets/routine.png
Labels: 🎨 Design, 🚀 Feat

#61 [design] todo list calendar chips width 조정
  src/components/chips/CalendarChip.tsx
  src/pages/Calendar/CalendarPage.tsx
  src/pages/Main/MainPage.tsx
Labels: 🎨 Design

#62 [feat] routine api
  src/App.tsx
  src/components/Calendar.tsx
  src/components/Layout/Header.tsx
  src/components/PopUpDatePicker.tsx
  src/components/chips/CalendarChip.tsx
  src/components/chips/StatusChip.tsx
  src/pages/Calendar/api/todoDayGroupedByCompanyType.ts
  src/pages/Career/components/CareerQuestion.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Main/components/CareerRecruitmentsStatus.tsx
  src/pages/RecruScheduleEnv/RecruScheduleEnvPage.tsx
  src/pages/Status/DetailStatusPage.tsx
  src/pages/Status/StatusPage.tsx
  src/pages/Status/components/Buttons/RecurringNoteButton.tsx
  src/pages/Status/components/Buttons/StatusButton.tsx
  src/pages/Status/components/Helpers/DetailStatusHelper.tsx
  src/pages/Status/components/Helpers/StatusHelper.tsx
  src/pages/Status/components/Todo/ScheduleField.tsx
  src/pages/Status/components/Todo/TodoComponent.tsx
  src/pages/Status/components/Todo/components/RoutineSettingsModal.tsx
  src/pages/Status/components/Todo/components/ScheduleField.tsx
  src/pages/Status/components/Todo/components/SettingsModal.tsx
  src/pages/Status/components/Todo/components/TodoSettingsModal.tsx
  src/shared/assets/hamburger-md-black.svg
  src/shared/assets/routine-delete.png
Labels: 🎨 Design, 🚀 Feat, 🏷 Fix

#64 [refactor] api 코드 일반화
  src/App.tsx
  src/components/Calendar.tsx
  src/components/TestCalendar.tsx
  src/pages/Calendar/api/calendarMonthPersonalWorksApiService.ts
  src/pages/Calendar/api/calendarMonthPersonalWorksType.ts
  src/pages/Calendar/api/calendarMonthRecruitmentsApiService.ts
  src/pages/Calendar/api/calendarMonthRecruitmentsType.ts
  src/pages/Calendar/api/personalScheduleApiService.ts
  src/pages/Calendar/api/personalScheduleType.ts
  src/pages/Calendar/api/todoDayGroupedByCompanyApiService.ts
  src/pages/Calendar/api/todoDayGroupedByCompanyType.ts
  src/pages/Main/api/alarmApiService.ts
  src/pages/Main/api/careerRecruitmentsStatusApiService.ts
  src/pages/Main/api/careerRecruitmentsStatusType.ts
  src/pages/Main/api/careerStatusesNumApiService.ts
  src/pages/Main/api/careerStatusesNumType.ts
  src/pages/Main/api/careerStatusesStageNumApiService.ts
  src/pages/Main/api/careerStatusesStageNumType.ts
  src/pages/Main/api/mainTodayApiService.ts
  src/pages/Main/components/CareerRecruitmentsStatus.tsx
  src/pages/Main/components/CareerStatusNumBoard.tsx
  src/pages/Main/components/CareerStatusStageNumBoard.tsx
  src/pages/RecruScheduleEnv/RecruScheduleEnvPage.tsx
  src/pages/RecruScheduleEnv/api/recruScheduleApiService.ts
  src/pages/RecruScheduleEnv/api/recruScheduleType.ts
  src/shared/api/axiosInstance.ts
  src/shared/api/recruitments.ts
  src/shared/api/routinesApiService.ts
  src/shared/api/routinesType.ts
  src/shared/api/todoApiService.ts
Labels: 🧹 Refactor

#66 [design] todo design modification
  src/components/TestCalendar.tsx
  src/pages/Calendar/components/PersonalScheduleList_API연동전.tsx
  src/pages/Calendar/components/TodoListEditable.tsx
  src/pages/Calendar/components/TodoListFixed.tsx
  src/pages/Calendar/components/TodoListFixed_20240906_API연동전.tsx
  src/pages/Calendar/components/TodoList_API연동전.tsx
  src/pages/RecruScheduleEnv/RecruScheduleEnvPage_연동전.tsx
  src/pages/Status/DetailStatusPage.tsx
  src/pages/Status/components/Todo/TodoComponent.tsx
  src/pages/Status/components/Todo/components/ScheduleField.tsx
Labels: 🎨 Design

#68 [fix] non-existent components import 삭제
  src/pages/Calendar/CalendarPage.tsx
  src/pages/Calendar/components/CalendarList.tsx
Labels: 🏷 Fix

#69 [fix] async error 해결
  src/pages/Calendar/components/TodoListEditable.tsx
  src/pages/Main/components/MainTodayList.tsx
Labels: 🏷 Fix

#70 [fix] debug useEffect
  src/components/Calendar.tsx
  src/pages/Calendar/CalendarPage.tsx
  src/pages/Calendar/components/TodoListEditable.tsx
  src/pages/Calendar/components/TodoListFixed.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Main/components/Alarm.tsx
Labels: 🏷 Fix

#72 Update README.md
  README.md
Labels: 📑 Docs
